trigger: 
- main
pr: none

pool: 
  vmImage: 'ubuntu-latest'
steps:
  - bash: |
      echo "hello Meghana"
    displayName: 'Greetings'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'this is coming from a plugin'
